server:
  port: 8080

#数据源配置 
spring:
  datasource:
    data-username: dbSource
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: taobang
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 20
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#Mybtais 相关配置      
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.avc.shiro.oauth2
